HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[0];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[1];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[2];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[3];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[4];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[5];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[6];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[7];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[8];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[9];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[10];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[11];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[12];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[13];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[14];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[15];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[16];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[17];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[18];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[19];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[20];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[21];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[22];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[23];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[24];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[25];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[26];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[27];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[28];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[29];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[30];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[31];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[32];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[33];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[34];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[35];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[36];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[37];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[38];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[39];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[40];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[41];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[42];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[43];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[44];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[45];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[46];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[47];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[48];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[49];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[50];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[51];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[52];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[53];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[54];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[55];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[56];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[57];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[58];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[59];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[60];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[61];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[62];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[63];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[64];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[65];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[66];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[67];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[68];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[69];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[70];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[71];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[72];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[73];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[74];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[75];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[76];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[77];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[78];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[79];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[80];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[81];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[82];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[83];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[84];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[85];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[86];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[87];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[88];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[89];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[90];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[91];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[92];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[93];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[94];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[95];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[96];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[97];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[98];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[99];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[100];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[101];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[102];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[103];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[104];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[105];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[106];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[107];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[108];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[109];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[110];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[111];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[112];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[113];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[114];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[115];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[116];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[117];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[118];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[119];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[120];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[121];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[122];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[123];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[124];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[125];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[126];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[127];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[128];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[129];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[130];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[131];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[132];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[133];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[134];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[135];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[136];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[137];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[138];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[139];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[140];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[141];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[142];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[143];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[144];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[145];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[146];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[147];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[148];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[149];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[150];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[151];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[152];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[153];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[154];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[155];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[156];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[157];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[158];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[159];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[160];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[161];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[162];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[163];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[164];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[165];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[166];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[167];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[168];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[169];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[170];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[171];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[172];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[173];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[174];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[175];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[176];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[177];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[178];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[179];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[180];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[181];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[182];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[183];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[184];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[185];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[186];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[187];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[188];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[189];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[190];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[191];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[192];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[193];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[194];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[195];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[196];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[197];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[198];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[199];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[200];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[201];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[202];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[203];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[204];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[205];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[206];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[207];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[208];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[209];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[210];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[211];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
HWREG(GPIO_PORTB_AHB_BASE + GPIO_O_DATA + (0xFF << 2)) = pattern[212];
asm volatile("nop");asm volatile("nop");asm volatile("nop"); asm volatile("nop"); asm volatile("nop");
